name: Run Tests

on:
  push:
    branches:
      - feature/homework-5

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_mysql

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Show files after composer install
        run: ls -la

      - name: Run PHPUnit
        run: vendor/bin/phpunit